language: cpp
sudo: true
dist: trusty

compiler:
    - g++

#Build steps
before_install:
    - sudo apt-get install libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-ttf2.0-dev -y
    - git clone https://github.com/ptitSeb/SDL_sound
    - cd SDL_sound
    - ./autogen.sh
    - ./configure --prefix=/usr --enable-sdl2=no
    - make
    - sudo make install
    - cd ..

script: make LINUX=1
